### ISSUE TITLE
Requires 1 positional argument 'Loader'

### ISSUE THREAD

**Issue by SinichiKudo02** [jayg996/BTC-ISMIR19#7]
May I know what version of python did you used in this case since I'm having an error
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    config = HParams.load("run_config.yaml")
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python37\BTC-ISMIR19\utils\hparams.py", line 29, in load
    return cls(**yaml.load(f))
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by usingnamespacestc** [comment]
Try this: return cls(**yaml.load(f, yaml.Loader)).

And if you meet other two issues, replace "np.float" in "transformer_modules.py" to "np.fload32", and "np.int" to "np.int_" in the "mir_eval" library I remember. Follow the Traceback to find the file.

That works for me.

**Comment by palachute** [comment]
It seems the version of "pyyaml" and "numpy" is too high.  When I use the 6.0.1 version of pyyaml and  numpy version >=1.24 also encounters the two questions.
Set the versions:  pyyaml==3.13, and numpy==1.23, That solves my problem.
